[package]
name = "blink_guard"
version = "0.1.0"
edition = "2024"

[target.'cfg(windows)'.dependencies]
ort = { version = "2.0.0-rc.13", features = ["directml"] }

[target.'cfg(target_os = "linux")'.dependencies]
ort = { version = "2.0.0-rc.13", features = ["cuda"] }

[target.'cfg(target_os = "macos")'.dependencies]
ort = { version = "2.0.0-rc.13", features = ["coreml"] }

[dependencies]
anyhow = "1.0"
crossbeam-channel = "0.5"
eframe = "0.27"
env_logger = "0.11"
image = "0.25"
imageproc = "0.25"
ndarray = "0.17.2"
log = "0.4"
notify-rust = "4.18.0"
rodio = "0.22.2"

[dependencies.nokhwa]
version = "0.10.11"
# Use the native input backends, enable WGPU integration
features = ["input-native", "output-wgpu"]
